### ISSUE TITLE
Wrong parameters for k8s deploy

### ISSUE THREAD

**Issue by SawasReaper** [CircleCI-Public/gcp-gke-orb#1]
I think the step with setting new image on k8s is doing sth wrong. Its line 37 in Orb Source: `kubectl set image deployment <<parameters.deployment>> <<parameters.container>>=<<parameters.image>>` If it is like that k8s can't pull image from registry. In think `kubectl set image deployment <<parameters.deployment>> <<parameters.container>>=<<parameters.registry-url>>/<<parameters.google-project-id>>/<<parameters.image>>:<parameters:tag>` should work. 

I've checked and solution from above works.

**Comment by zackijack** [comment]
Hi @SawasReaper, I have tried and there are no problems with the command.
I think the `image` parameter here is general, so you can fill it with only the image name if it's from the docker hub (e.g. `nginx` or `bitnami/redis`) or with full url if it's from your registry (e.g. `asia.gcr.io/your-project-id/your-image:2.1`).

**Comment by felicianotech** [comment]
Hi @SawasReaper,

Did zackijack's answer work for you?

**Comment by SawasReaper** [comment]
Hi @felicianotech ,
I don't use it anymore so I don't really know if @zackijack answer is correct. I think my solution was good.

Up to you 😉

**Comment by felicianotech** [comment]
We'll revisit this if more people bring it up.

**Comment by leungandrew** [comment]
What @SawasReaper mentioned should be the correct behaviour.
If you look at the `gcp-gke/publish-and-rollout-image` job, how it uses <<parameter.image>> in the `gcr/build-image` step and how it uses it in `rollout-image` do not satisfy the single `image` parameter to the job.

In `gcr/build-image`, it will create an image at `gcr.io/$GOOGLE_PROJECT_ID/<<parameter.image>>`

In `rollout-image`, it simply applies `<<parameter.image>>` without the full image path, and therefore setting the deployment image will not work.  

This should be reopened as in its current state, the `gcp-gke/publish-and-rollout-image` job will not work.

**Comment by lokst** [comment]
@leungandrew Thanks for highlighting the issue. We'll address this bug.
