### ISSUE TITLE
Namespace support for updating deployments

### ISSUE THREAD

**Issue by willjschmitt** [CircleCI-Public/gcp-gke-orb#17]
### Orb version
0.2.0

### What happened
(actual container, deployment, etc., names replaced)
```
$ #!/bin/bash -eo pipefail
gcloud container clusters get-credentials $GOOGLE_CLUSTER_NAME
kubectl set image deployment deployment-foo container-foo=gcr.io/project-foo/container-foo:$CIRCLE_SHA1

Fetching cluster endpoint and auth data.
kubeconfig entry generated for cluster-foo.
Error from server (NotFound): deployments.extensions "deployment-foo" not found
Exited with code 1
```

### Expected behavior
`deployment-foo` is in `namespace-foo`, so `kubectl set image deployment` uses default namesapce.

I would expect to be able to set the namespace as a parameter for both jobs `publish-and-rollout-image` and `rollout-image`

**Comment by willjschmitt** [comment]
Just saw actually that @duksis has PR #7 open, which would satisfy this need.

**Comment by lokst** [comment]
We'll look into this 👍
