### ISSUE TITLE
Error when getting cluster credential

### ISSUE THREAD

**Issue by zackijack** [CircleCI-Public/gcp-gke-orb#2]
In this orb you use `deployment` name instead of `cluster` name when you run `gcloud container clusters get-credentials`, and this causes an error.

**Comment by zackijack** [comment]
Hi @iynere, I just open a PR to fix this issue.

Thanks.

**Comment by WalkerGriggs** [comment]
@iynere @zackijack Thank's for getting on this. I was just about to submit an issue myself, but looks like you both have this covered. Do you have an ETA for when this will get merged?
