### ISSUE TITLE
Cannot run update-kubeconfig-with-credentials job

### ISSUE THREAD

**Issue by krtk6160** [CircleCI-Public/gcp-gke-orb#26]
### Orb version
1.0.4

### What happened
When trying to run the `update-kubeconfig-with-credentials` job, Circleci build fails with `Cannot find a definition for job named gcp-gke/update-kubeconfig-with-credentials`.

### Expected behavior
The `update-kubeconfig-with-credentials` is a documented job and its definition should be found by circleci.

**Comment by lokst** [comment]
@krtk6160 That is actually a command instead of a job, hence it should be used in a job that you define

**Comment by krtk6160** [comment]
@lokst  Sorry, I had no idea commands were a separate thing. I'm just starting out with circleci.
Can you point me to any examples or docs that explain usage of commands? I can't seem to find any.

**Comment by krtk6160** [comment]
I finally found documentation regarding commands. Closing this now.
