### ISSUE TITLE
create/delete namespace feature

### ISSUE THREAD

**Issue by rusenask** [CircleCI-Public/gcp-gke-orb#28]
Hello, thanks for the orb! Do you have plans to add create/delete namespace commands? That would be useful in tests as we are exploring to run tests on a remote GKE cluster where PR commits could be tested in separate namespaces. 
For now I am planning to do the setup myself but it would be nice to see it added here too.

**Comment by EricRibeiro** [comment]
Hi @rusenask, thank you for the suggestion!

We try to avoid creating commands that translate to a straightforward command line as it would be with namespace creation/deletion. It would add an extra layer of indirection to a command that doesn't require it.

If you disagree or have a scenario where namespace creation/deletion would include more complexity hence justifying the command creation, feel free to open another issue to discuss it.
