### ISSUE TITLE
docker build fails during job publish-and-rollout-image: dockerfile-dir ignored

### ISSUE THREAD

**Issue by christianskovholm** [CircleCI-Public/gcp-gke-orb#30]
### Orb version

1.0.4

### What happened

`docker build` fails during job: publish-and-rollout-image. I use dockerfile-die param to specify the location of the dockerfile. The job run can be viewed at: https://app.circleci.com/pipelines/github/christianskovholm/portfolioapp/176/workflows/d9772f1e-ed40-42c7-a5b9-0ae81efbcabb/jobs/232

### Expected behavior

`docker build` should succeed. dockerfile-dir param should set the path/context of the docker build command, however, it seems to be ignored and instead defaults to `${HOME}/project`.

**Comment by dsayling** [comment]
Hi there! There were some updates to the dependent orbs that needed to be pulled in. As a result, you'll need to update to latest version 1.1.0, https://circleci.com/orbs/registry/orb/circleci/gcp-gke and you'll need to set the `docker-context` parameter to the desired path (in your case I believe you want the same as `dockerfile-dir`).
