### ISSUE TITLE
perform-login fails due to missing region that is set in env variable

### ISSUE THREAD

**Issue by villesau** [CircleCI-Public/gcp-gke-orb#51]
## Orb version:

1.4.0

## What happened:

Step `Update kubeconfig with cluster credentials` failed to following error:

```
#!/bin/bash -eo pipefail
gcloud container clusters get-credentials my-cluster

ERROR: (gcloud.container.clusters.get-credentials) One of [--zone, --region] must be supplied: Please specify location.

Exited with code exit status 1
CircleCI received exit code 1
```

when running with following config:

```
      - gcp-gke/update-kubeconfig-with-credentials:
          cluster: my-cluster
          perform-login: true
```
and `GOOGLE_COMPUTE_REGION` environment variable in place

## Expected behavior:

It should work. I provide the GOOGLE_COMPUTE_REGION as an environment variable.

**Comment by mariachugunova** [comment]
+1

**Comment by mareksuscak** [comment]
This is actually still an issue even on with the latest version of Cloud SDK 410.0.0. The problem is that GKE regional clusters require you to provide the `--region` option on the command line even if the default region is configured globally.

**Comment by EricRibeiro** [comment]
> This is actually still an issue even on with the latest version of Cloud SDK 410.0.0. The problem is that GKE regional clusters require you to provide the `--region` option on the command line even if the default region is configured globally.

Thanks for the additional information! Do you have a link where I can read more about this?

I'm considering creating an `additional_args` parameter to allow the passing of region in the `update-kubeconfig-with-credentials` command. It will fix this issue and allow for more flexibility.

**Comment by mareksuscak** [comment]
> > This is actually still an issue even on with the latest version of Cloud SDK 410.0.0. The problem is that GKE regional clusters require you to provide the `--region` option on the command line even if the default region is configured globally.
> 
> Thanks for the additional information! Do you have a link where I can read more about this?
> 
> I'm considering creating an `additional_args` parameter to allow the passing of region in the `update-kubeconfig-with-credentials` command. It will fix this issue and allow for more flexibility.

It's not documented very well to be honest. The only trace of this I've recently found when I was setting up two clusters (dev was zonal, prod was regional) is the gcloud SDK documentation:

https://cloud.google.com/sdk/gcloud/reference/container/clusters/get-credentials

Here, the `zone` flag is said to override the default zone but there's no such thing noted for the `region` flag. Thus I assumed it was mandatory for regional clusters. One thing I haven't tried was omitting the `zone` for a regional cluster but I always pass in both zone and region into every command.
