### ISSUE TITLE
Add repo link to orb description

### ISSUE THREAD

**Issue by KyleTryon** [CircleCI-Public/gcp-gke-orb#6]
Add git repo link to orb description.

Guideline: 
https://github.com/CircleCI-Public/Orb-Policies/blame/master/Orb%20Best%20Practices%20Guidelines.md#L13

**Comment by gagandeepp** [comment]
I will take care of this one

**Comment by gagandeepp** [comment]
@KyleTryon Can you please change the label to work in progress ,once an issue been assigned to some one? This will help other person to not work on the same issue.

**Comment by KyleTryon** [comment]
@gagandeepp for this event we are leaving issues open until PRs become merged. This will allow multiple people to tackle a problem differently so we can select the best option and allow more people to participate in hacktoberfest. We have a lot of first time contributors so we don't want to close the door too early.

**Comment by TheHandsomeCoder** [comment]
@KyleTryon Could you elaborate more as to what you're like done as part of this issue?

Are you looking for this repo to have a link to the link you posted above?

**Comment by KyleTryon** [comment]
A PR has already been accepted for this issue. Thank you.
https://github.com/CircleCI-Public/gcp-gke-orb/pull/11
